### ISSUE TITLE
Major 도매인 관련 API들 구현 

### ISSUE THREAD

**Issue by gomster96** [gomster96/CSEE-SelfCheck#19]
### Description
- Major 도매인 관련 CRUD API를 구현한다. 

### Todo
- [ ] Major를 생성하는 기능을 하는 API를 구현한다.
- [ ] Major를 Read 하는 기능을 하는 API를 구현한다. 
- [ ] Major를 수정하는 기능을 하는 API를 구현한다. 
- [ ] Major를 삭제하는 기능을 하는 API 를 구현한다. 

### ETC
