### ISSUE TITLE
백엔드  도메인 구조 생성 

### ISSUE THREAD

**Issue by gomster96** [gomster96/CSEE-SelfCheck#3]
### Description
package by layer or package by feature 패키지 구조 결정 후, 도메인 구조 생성

### Todo
- [ ] 패키지 구조 공부해오기
  - https://medium.com/sahibinden-technology/package-by-layer-vs-package-by-feature-7e89cde2ae3a
- [ ] 패키지 구조 결정
- [ ] 도메인 구조 생성  

### ETC
