### ISSUE TITLE
관리자 페이지 학생 조회 API 구현 

### ISSUE THREAD

**Issue by gomster96** [gomster96/CSEE-SelfCheck#36]
### Description
관리자 페이지에서 토글에 따라 학생들의 정보를 조회할 수 있도록, API를 구현한다. 

### Todo
- [ ] 과목별로 들어오는 정보에 따라 필터기능
- [ ] 학기수 별로 들어오는 정보에 따라 필터기능
- [ ] 이수가능 학생 별로 필터 기능 구현
- [ ] 비고 데이터 구현
  - [ ] 수강 불가능일 경우 왜 불가능한지의 여부 출력
  - [ ] 병수 수강인 과목이 있으면, 어떤 과목이 병수인지 출력 

### ETC
