### ISSUE TITLE
관리자페이지 프론트와 벡엔드 연결

### ISSUE THREAD

**Issue by gomster96** [gomster96/CSEE-SelfCheck#61]
### Description
프론트와 벡엔드 페이지 연결 

### Todo
- [ ] 토글 구현 및 관련해서 fetch 할 수 있도록 프론트 코드 구현
- [ ] search에도 fetch할 수 있도록 구현
- [ ] search와 toggle이 한번에 처리되도록 쿼리문 변경
- [ ] excel import fetch 구현, 
- [ ] 한 파일내에서 lecture, major, referenceUser 처리할 수 있도록 벡엔드 코드 수정하기 
- [ ] excel export fetch 구현 
- [ ] 알맞은 데이터들이 들어왔는지 확인  

### ETC
