### ISSUE TITLE
mypage, selfcheck css 수정

### ISSUE THREAD

**Issue by kimjueun1** [gomster96/CSEE-SelfCheck#65]
### Description
mypage, selfcheck css수정

### Todo
- [x] 셀프체크 - [버튼] 다시하기 → 초기화로 워딩 변경
- [ ] 셀프체크 - 초기화 구현
- [x] 마이페이지 - 제출하기 버튼 삭제 (주은)
- [x] 마이페이지 - 설명 지우기 (주은) 
- [ ] 수정하기 버튼 누르면 selfcheck로 연결
### ETC
