### ISSUE TITLE
관리자 페이지 데이터 필터 기능 API 기능 수정 및 FE state 정리 

### ISSUE THREAD

**Issue by gomster96** [gomster96/CSEE-SelfCheck#75]
### Description
관리자 페이지 데이터 필터 기능 API 기능 수정 및 FE state 정리 

### Todo
- [x]  BE : 데이터를 전공, 학기수, 결과에 따라 가지고오던 API와 검색결과에 관련한 API 기능 합치기 
    - [x]  BE : 병수예정, 공프기 수강 불가능 데이터도 가져오기 
- [x]  FE : 데이터를 fetch해오는 state 정리 
- [x]  FE : 병수예정, 공프기 수강 불가능인 이유 적기 

### ETC
